#!/bin/bash
name=$1
contest_code=${name:0:3}
problem_code=${name:4:1}
pathe='/home/'$USER'/GoCF/sukeesh.txt'
DONE=false
todo=0
tot=0
until $DONE
do
  read line || DONE=true
  if [[ ${line:0:1} == $problem_code ]]; then
	tot=${line:2:1}
  fi
done < $pathe
fla=0

g++ $name || fla=1
if [ $fla -eq 1 ]
then
	echo -e "\n\033[1;31m : Compilation Error\e[0m"
	exit
fi
 
todo=0
while [[ $todo -lt $tot ]]
do
	u=1
	todo=$((todo+1))
	pathe='/home/'$USER'/GoCF/'
	temppath=$pathe$problem_code$todo'.in'
	x=0
	timeout 2 ./a.out <$temppath> $pathe$problem_code$todo'.rc' || x=1
	diff --brief <(sort $pathe$problem_code$todo'.out') <(sort $pathe$problem_code$todo'.rc') >/dev/null
        comp_val=$?

	if [ $x -eq 1 ]
	then
		echo -e "\e[1m>>Running test "$todo"\e[0m : \033[1;34m [Time limit exceeded]\e[0m"
	elif [ $comp_val -eq 1 ]
	then
		echo -e "\n"
		echo -e "\e[1m>>Running test "$todo"\e[0m : \e[91m [Wrong Answer]\e[0m"
		echo -e "\n\033[1;35mInput :\e[0m"
		cat < $temppath
		echo -e "\n\033[1;31mRecieved Ouput :\e[0m "
		cat < $pathe$problem_code$todo'.rc'
		echo -e "\n\033[1;32mExpected Output :\e[0m"
                cat < $pathe$problem_code$todo'.out'
	else
		echo -e "\e[1m>>Running test "$todo"\e[0m : \033[92m [Pretest Passed]\e[0m"
	fi
done
