#!/bin/bash
name=$1
contest_code=${name:0:3}
problem_code=${name:4:1}
pathe='/home/'$USER'/GoCF/sukeesh.txt'
DONE=false
todo=0
tot=0
until $DONE
do
  read line || DONE=true
  if [[ ${line:0:1} == $problem_code ]]; then
	tot=${line:2:1}
  fi
done < $pathe
g++ $name
todo=0
while [[ $todo -lt $tot ]]
do
	u=1
	todo=$((todo+1))
	pathe='/home/'$USER'/GoCF/'
	temppath=$pathe$problem_code$todo'.in'
	./a.out <$temppath> $pathe$problem_code$todo'.rc'
	diff --brief <(sort $pathe$problem_code$todo'.out') <(sort $pathe$problem_code$todo'.rc') >/dev/null
	comp_val=$?
	if [ $comp_val -eq 1 ]
	then
		echo -e "\e[1m Running test \e[0m"$todo"\e[91m : [Wrong Answer]\e[0m"
	else
		echo -e "\e[1m Running test \e[0m"$todo"\e[92m : [Pretest Passed]\e[0m"
	fi
done 
